---
title: perSEVERE - FRC Team 5962
timezone: UTC
collections:
  mentors:
    title: Mentors
    output: false
  posts:
    title: Posts
    output: true
  students:
    title: Students
    output: false
  tags:
    title: Tags
    output: true
    permalink: "/tags/:name/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: "/tags/"
  values:
    layout: default
- scope:
    path: ''
    type: mentors
  values:
    role: 
    order-number: 100
- scope:
    path: ''
    type: students
  values:
    role: 
    grad-year: 
    order-number: 254
permalink: "/news/:title"
description: Team 5962, also known as perSEVERE, is a FIRST Robotics Competition (FRC)
  team from Lowell, Massachusetts. Since our rookie season in 2016, we've welcomed
  middle and high school students from the Merrimack Valley and bring STEM to our
  community through many outreach events.
url: https://frcpersevere.com
nav-links:
- name: About
  url: "/about"
- name: News
  url: "/news"
- name: Robots
  url: "/robots"
- name: Outreach
  url: "/outreach"
- name: Resources
  url: "/resources"
- name: Sponsors
  url: "/sponsors"
- name: Contact
  url: "/contact"
sass:
  style: compressed
plugins:
- jekyll/tagging
tag_page_layout: tag
tag_page_dir: "/tags"
