---
title: perSEVERE - FRC Team 5962
timezone: UTC
collections:
  mentors:
    title: Mentors
    output: false
  posts:
    title: Posts
    output: true
  students:
    title: Students
    output: false
  uploads:
    title: Uploads
    output: true
  tags:
    output: true
    permalink: /tags/:name/
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: mentors
  values: 
    role: 
    order-number: 100
- scope:
    path: ''
    type: students
  values:
    role: 
    grad-year: 
    order-number: 254
permalink: "/news/:title"
description: Team 5962, also known as perSEVERE, is a FIRST Robotics Competition (FRC)
  team from Lowell, Massachusetts. Since our rookie season in 2016, we've welcomed
  middle and high school students from the Merrimack Valley and bring STEM to our
  community through many outreach events.
url: https://frcpersevere.com
nav-links:
- name: About
  url: "/about"
- name: News
  url: "/news"
- name: Outreach
  url: "/outreach"
- name: Sponsors
  url: "/sponsors"
- name: Contact
  url: "/contact"
sass:
  style: compressed
